map_type: costmap

obstacle_range: 4.0
raytrace_range: 5.0

transform_tolerance: 1.0

# define the coordinates of the robot outline
# footprint: [[0.3,0.3],[0.3,-0.3],[-0.3,-0.3],[-0.3,0.3]]
robot_radius: 0.4

observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: hokuyo,
  data_type: LaserScan,
  topic: /dumpster/laser/scan,
  marking: true,
  clearing: true
}
